import { fromUrl } from 'geotiff';
import proj4 from 'proj4';
import { CogReaderError, type CogBandStatistics, type CogReadOptions, type CogWindowResult, type GeoJsonPolygon } from './types.js';

function extent(polygon: GeoJsonPolygon): [number, number, number, number] { const points = polygon.coordinates[0] ?? []; if (points.length < 4) throw new CogReaderError('COG_INVALID_ASSET', 'Polygon has no usable ring'); const xs = points.map((point) => point[0] ?? 0); const ys = points.map((point) => point[1] ?? 0); return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)]; }
function stats(values: ArrayLike<number>, bytesRead: number): CogBandStatistics { let sum = 0; let count = 0; for (let index = 0; index < values.length; index += 1) { const value = values[index]; if (typeof value === 'number' && Number.isFinite(value)) { sum += value; count += 1; } } if (count === 0) throw new CogReaderError('COG_NO_DATA', 'COG window contains no valid pixels'); return { mean: sum / count, validPixelCount: count, bytesRead }; }

export async function readCogWindow(red: CogReadOptions, nir: CogReadOptions): Promise<CogWindowResult> { const timeoutMs = red.timeoutMs ?? 10_000; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); const originalFetch = globalThis.fetch; let bytesRead = 0; const pending: Promise<void>[] = []; globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => { const response = await originalFetch(input, init); const copy = response.clone(); pending.push(copy.arrayBuffer().then((data) => { bytesRead += data.byteLength; })); return response; }; try { const redTiff = await fromUrl(red.url, { signal: controller.signal }); const nirTiff = await fromUrl(nir.url, { signal: controller.signal }); const redImage = await redTiff.getImage(); const nirImage = await nirTiff.getImage(); const redWindow = windowFor(redImage.getBoundingBox(), redImage.getWidth(), redImage.getHeight(), red.polygon, redImage.getGeoKeys()); const nirWindow = windowFor(nirImage.getBoundingBox(), nirImage.getWidth(), nirImage.getHeight(), nir.polygon, nirImage.getGeoKeys()); const [redRaster, nirRaster] = await Promise.all([redImage.readRasters({ window: redWindow, samples: [0] }), nirImage.readRasters({ window: nirWindow, samples: [0] })]); await Promise.all(pending); const redStats = stats(redRaster[0] as ArrayLike<number>, bytesRead); const nirStats = stats(nirRaster[0] as ArrayLike<number>, 0); return { red: redStats, nir: nirStats, meanReflectance: (redStats.mean + nirStats.mean) / 2, bytesRead }; } catch (error: unknown) { if (error instanceof CogReaderError) throw error; if (error instanceof Error && error.name === 'AbortError') throw new CogReaderError('COG_TIMEOUT', `COG read timed out after ${timeoutMs}ms`, error); throw new CogReaderError('COG_READ_ERROR', 'Unable to read COG window', error); } finally { globalThis.fetch = originalFetch; clearTimeout(timer); } }
function windowFor(bounds: number[], imageWidth: number, imageHeight: number, polygon: GeoJsonPolygon, geoKeys: Record<string, unknown>): [number, number, number, number] { if (bounds.length < 4 || imageWidth < 1 || imageHeight < 1) throw new CogReaderError('COG_INVALID_ASSET', 'COG raster metadata is invalid'); const projected = projectExtent(polygon, geoKeys); const [minX, minY, maxX, maxY] = projected; const imageMinX = bounds[0] ?? 0; const imageMinY = bounds[1] ?? 0; const imageMaxX = bounds[2] ?? 0; const imageMaxY = bounds[3] ?? 0; if (imageMaxX <= imageMinX || imageMaxY <= imageMinY) throw new CogReaderError('COG_INVALID_ASSET', 'COG bounding box has zero area'); const x0 = Math.max(0, Math.min(imageWidth - 1, Math.floor((minX - imageMinX) / (imageMaxX - imageMinX) * imageWidth))); const y0 = Math.max(0, Math.min(imageHeight - 1, Math.floor((imageMaxY - maxY) / (imageMaxY - imageMinY) * imageHeight))); const x1 = Math.max(x0 + 1, Math.min(imageWidth, Math.ceil((maxX - imageMinX) / (imageMaxX - imageMinX) * imageWidth))); const y1 = Math.max(y0 + 1, Math.min(imageHeight, Math.ceil((imageMaxY - minY) / (imageMaxY - imageMinY) * imageHeight))); return [x0, y0, x1, y1]; }
function projectExtent(polygon: GeoJsonPolygon, geoKeys: Record<string, unknown>): [number, number, number, number] { const code = geoKeys.ProjectedCSTypeGeoKey; const points = polygon.coordinates[0] ?? []; const projected = typeof code === 'number' && code !== 4326 ? points.map((point) => proj4('EPSG:4326', `EPSG:${code}`, [point[0] ?? 0, point[1] ?? 0])) : points; const xs = projected.map((point) => point[0] ?? 0); const ys = projected.map((point) => point[1] ?? 0); return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)]; }
