import { findBandAsset, fetchSatelliteMetadata } from '@orbibound-ai/stac-fetcher';
import { readCogWindow } from '@orbibound-ai/cog-reader';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@orbibound-ai/database';
import { claimDueAssets, updateAsset, updateSchedule, writeProcessingLog } from './repository.js';
import { processAsset } from './processor.js';
import type { ClaimedAsset, WorkerDependencies } from './types.js';

type WorkerClient = SupabaseClient<Database>;
interface Polygon { type: 'Polygon'; coordinates: number[][][] }
interface ProcessingRow { scene_id: string | null; run_at: string; current_value: number | null; cloud_cover: number | null }
function polygon(value: unknown): Polygon { if (typeof value !== 'object' || value === null || (value as { type?: unknown }).type !== 'Polygon') throw new Error('INVALID_GEOMETRY'); return value as Polygon; }
function bbox(value: unknown): { minLng: number; minLat: number; maxLng: number; maxLat: number } { const points = polygon(value).coordinates[0] ?? []; const lngs = points.map((point) => point[0] ?? 0); const lats = points.map((point) => point[1] ?? 0); return { minLng: Math.min(...lngs), minLat: Math.min(...lats), maxLng: Math.max(...lngs), maxLat: Math.max(...lats) }; }

export function createDependencies(client: WorkerClient, apiUrl: string, collection = 'sentinel-2-l2a', workerId?: string): WorkerDependencies { const id = workerId ?? `worker-${process.pid}`; return { workerId: id, stacApiUrl: apiUrl, stacCollection: collection, fetchMetadata: async (asset: ClaimedAsset) => { const result = await fetchSatelliteMetadata({ bbox: bbox(asset.geo_boundary), daysBack: 30, maxCloudCover: 80, limit: 5 }, { apiUrl, collection }); const scene = result?.scenes[0]; if (scene === undefined) throw new Error('STAC_NO_SCENES'); return { sceneId: scene.id, datetime: scene.datetime, cloudCover: scene.cloudCover, redHref: findBandAsset(scene, 'red').href, nirHref: findBandAsset(scene, 'nir').href }; }, readCog: async (asset, scene) => { const cog = await readCogWindow({ url: scene.redHref, polygon: polygon(asset.geo_boundary) }, { url: scene.nirHref, polygon: polygon(asset.geo_boundary) }); return { bytesRead: cog.bytesRead, scene: { sceneId: scene.sceneId, datetime: scene.datetime, cloudCover: scene.cloudCover, meanReflectance: cog.meanReflectance } }; }, loadHistory: async (assetId: string) => { const { data, error } = await client.from('processing_logs').select('scene_id,run_at,current_value,cloud_cover').eq('asset_id', assetId).eq('status', 'succeeded').not('current_value', 'is', null).order('run_at', { ascending: false }).limit(20); if (error) throw error; const rows = data as ProcessingRow[]; return rows.filter((row) => row.scene_id !== null && row.current_value !== null && row.cloud_cover !== null).map((row) => ({ sceneId: row.scene_id as string, datetime: row.run_at, meanReflectance: row.current_value as number, cloudCover: row.cloud_cover as number })); }, updateAsset: (assetId, patch) => updateAsset(client, assetId, patch), writeLog: (entry) => writeProcessingLog(client, entry), updateSchedule: (assetId, success, refreshDays, worker, now) => updateSchedule(client, assetId, success, refreshDays, worker, now) }; }
export async function claimAndProcess(client: WorkerClient, apiUrl: string, collection = 'sentinel-2-l2a', workerId?: string, maxAssets = 50): Promise<void> { const id = workerId ?? `worker-${process.pid}`; const assets = await claimDueAssets(client, id, maxAssets); const dependencies = createDependencies(client, apiUrl, collection, id); for (const asset of assets) await processAsset(asset, dependencies); }
