import type { CreateAssetInput, GeoJsonPolygon, UpdateAssetInput } from '@orbibound-ai/backend';
import { BackendError } from '@orbibound-ai/backend';

function record(value: unknown): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new BackendError('INVALID_ASSET_INPUT', 'Request body must be an object'); return value as Record<string, unknown>; }
function polygon(value: unknown): GeoJsonPolygon { return value as GeoJsonPolygon; }
function frequency(value: unknown): 1 | 3 | 5 | 7 | undefined { if (value === undefined) return undefined; if (value === 1 || value === 3 || value === 5 || value === 7) return value; throw new BackendError('INVALID_ASSET_INPUT', 'refreshFrequencyDays must be 1, 3, 5, or 7'); }
function threshold(value: unknown): number | undefined { if (value === undefined) return undefined; if (typeof value !== 'number') throw new BackendError('INVALID_ASSET_INPUT', 'alertThreshold must be a number'); return value; }
export function parseCreateAssetInput(value: unknown): CreateAssetInput { const body = record(value); if (typeof body.assetName !== 'string' || body.geoBoundary === undefined) throw new BackendError('INVALID_ASSET_INPUT', 'assetName and geoBoundary are required'); const input: CreateAssetInput = { assetName: body.assetName, geoBoundary: polygon(body.geoBoundary) }; const refreshFrequencyDays = frequency(body.refreshFrequencyDays); const alertThreshold = threshold(body.alertThreshold); if (refreshFrequencyDays !== undefined) input.refreshFrequencyDays = refreshFrequencyDays; if (alertThreshold !== undefined) input.alertThreshold = alertThreshold; return input; }
export function parseUpdateAssetInput(value: unknown): UpdateAssetInput { const body = record(value); const input: UpdateAssetInput = {}; if (body.assetName !== undefined) { if (typeof body.assetName !== 'string') throw new BackendError('INVALID_ASSET_INPUT', 'assetName must be a string'); input.assetName = body.assetName; } if (body.geoBoundary !== undefined) input.geoBoundary = polygon(body.geoBoundary); const refreshFrequencyDays = frequency(body.refreshFrequencyDays); const alertThreshold = threshold(body.alertThreshold); if (refreshFrequencyDays !== undefined) input.refreshFrequencyDays = refreshFrequencyDays; if (alertThreshold !== undefined) input.alertThreshold = alertThreshold; return input; }
